/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eni.m1.hibernate.panels;

import eni.m1.hibernate.dao.LieuDAO;
import eni.m1.hibernate.entities.Lieu;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author shirleyodon
 */
public class LieuPanel extends javax.swing.JPanel {

    /**
     * Creates new form LieuPanel
     */
    private DefaultTableModel model;
    private final LieuDAO dao=new LieuDAO();
    
    public LieuPanel() {
        initComponents();
        initModel();
        fillTableModel(dao.listerLieu());
    }
    
    private void initModel(){
        model=(DefaultTableModel)placeTable.getModel();
    }
    
    private void fillTableModel(List<Lieu> list){
        if(list!=null){
            model.setRowCount(0);
            for(Lieu l: list){
                model.addRow(new Object[]{
                    l.getFormattedCodeLieu(), l.getDesignation(), l.getProvince()
                });
            }
            placeTable.setModel(model);
        }
    }
    
    private void addTableRow(Lieu l){
        if(l!=null){
            model.addRow(new Object[]{
                l.getFormattedCodeLieu(), l.getDesignation(), l.getProvince()
            });
            placeTable.setModel(model);
        }
    }
    
    private void editTableRow(int i, String code, String design, String province){
        try{
            model.setValueAt(code, i, 0);
            model.setValueAt(design, i, 1);
            model.setValueAt(province, i, 2);
            placeTable.setModel(model);
        }catch(Exception ex){
            System.err.println("\nErreur causée par editTableRow() de LieuPanel !\n"+ex);
        }
    }
    
    private void removeTableRow(int i){
        try{
            model.removeRow(i);
            placeTable.setModel(model);
        }catch(Exception ex){
            System.err.println("\nErreur causée par removeTableRow() de LieuPanel !\n"+ex);
        }
    }
    
    private void eraseFields(){
        codeLieuField.setText("");
        designationField.setText("");
        provinceField.setText("");
        searchField.setText("");
    }
    
    private boolean isEmpty(JTextField f){
        return f.getText().equals("");
    }
    
    private boolean estValide(String fcl){
        if(fcl.charAt(0) != 'L') return false;
        try{
            Integer.parseInt(fcl.substring(1));
            return true;
        }catch(NumberFormatException ex){
            System.err.println("\nLe code lieu saisi est invalide !\n"+ex);
            return false;
        }
    }
    
    private void move(int i){
        try{
            codeLieuField.setText(model.getValueAt(i, 0).toString());
            designationField.setText(model.getValueAt(i, 1).toString());
            provinceField.setText(model.getValueAt(i, 2).toString());
        }catch(Exception ex){
            System.err.println("\nErreur causée par move() de LieuPanel !\n"+ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bodyPanel = new javax.swing.JPanel();
        listPanel = new javax.swing.JPanel();
        placeTableScroll = new javax.swing.JScrollPane();
        placeTable = new javax.swing.JTable();
        searchPanel = new javax.swing.JPanel();
        byLabel = new javax.swing.JLabel();
        searchTypeComboBox = new javax.swing.JComboBox<>();
        searchField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        infoPanel = new javax.swing.JPanel();
        codeLieuLabel = new javax.swing.JLabel();
        designationLabel = new javax.swing.JLabel();
        provinceLabel = new javax.swing.JLabel();
        codeLieuField = new javax.swing.JTextField();
        designationField = new javax.swing.JTextField();
        provinceField = new javax.swing.JTextField();
        operationPanel = new javax.swing.JPanel();
        addButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        refreshButton = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(740, 450));

        bodyPanel.setBackground(new java.awt.Color(33, 47, 61));

        listPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Liste des lieux", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Trebuchet MS", 1, 22), new java.awt.Color(236, 240, 241))); // NOI18N
        listPanel.setOpaque(false);
        listPanel.setPreferredSize(new java.awt.Dimension(484, 297));

        placeTable.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        placeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Code", "Designation", "Province"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        placeTable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        placeTable.setRowHeight(20);
        placeTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                placeTableMouseClicked(evt);
            }
        });
        placeTableScroll.setViewportView(placeTable);

        javax.swing.GroupLayout listPanelLayout = new javax.swing.GroupLayout(listPanel);
        listPanel.setLayout(listPanelLayout);
        listPanelLayout.setHorizontalGroup(
            listPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, listPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(placeTableScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );
        listPanelLayout.setVerticalGroup(
            listPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(placeTableScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        searchPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Recherche", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Trebuchet MS", 1, 22), new java.awt.Color(236, 240, 241))); // NOI18N
        searchPanel.setOpaque(false);

        byLabel.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        byLabel.setForeground(new java.awt.Color(236, 240, 241));
        byLabel.setText("Par");

        searchTypeComboBox.setBackground(new java.awt.Color(86, 101, 115));
        searchTypeComboBox.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        searchTypeComboBox.setForeground(new java.awt.Color(255, 250, 250));
        searchTypeComboBox.setMaximumRowCount(2);
        searchTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Code lieu", "Mot-clef" }));

        searchField.setBackground(new java.awt.Color(86, 101, 115));
        searchField.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        searchField.setForeground(new java.awt.Color(255, 250, 250));
        searchField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        searchButton.setBackground(new java.awt.Color(86, 101, 115));
        searchButton.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        searchButton.setForeground(new java.awt.Color(255, 255, 255));
        searchButton.setText("OK");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout searchPanelLayout = new javax.swing.GroupLayout(searchPanel);
        searchPanel.setLayout(searchPanelLayout);
        searchPanelLayout.setHorizontalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(byLabel)
                .addGap(18, 18, 18)
                .addComponent(searchTypeComboBox, 0, 99, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(searchField, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(searchButton, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
        searchPanelLayout.setVerticalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(byLabel)
                    .addComponent(searchTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        infoPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Info sur le lieu", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Trebuchet MS", 1, 22), new java.awt.Color(236, 240, 241))); // NOI18N
        infoPanel.setOpaque(false);

        codeLieuLabel.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        codeLieuLabel.setForeground(new java.awt.Color(236, 240, 241));
        codeLieuLabel.setText("Code");

        designationLabel.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        designationLabel.setForeground(new java.awt.Color(236, 240, 241));
        designationLabel.setText("Designation");

        provinceLabel.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        provinceLabel.setForeground(new java.awt.Color(236, 240, 241));
        provinceLabel.setText("Province");

        codeLieuField.setEditable(false);
        codeLieuField.setBackground(new java.awt.Color(86, 101, 115));
        codeLieuField.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        codeLieuField.setForeground(new java.awt.Color(255, 250, 250));
        codeLieuField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        designationField.setBackground(new java.awt.Color(86, 101, 115));
        designationField.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        designationField.setForeground(new java.awt.Color(255, 250, 250));
        designationField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        provinceField.setBackground(new java.awt.Color(86, 101, 115));
        provinceField.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        provinceField.setForeground(new java.awt.Color(255, 250, 250));
        provinceField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout infoPanelLayout = new javax.swing.GroupLayout(infoPanel);
        infoPanel.setLayout(infoPanelLayout);
        infoPanelLayout.setHorizontalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(designationLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                    .addComponent(provinceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(codeLieuLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(designationField)
                    .addComponent(provinceField)
                    .addGroup(infoPanelLayout.createSequentialGroup()
                        .addComponent(codeLieuField)
                        .addGap(56, 56, 56)))
                .addContainerGap())
        );
        infoPanelLayout.setVerticalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codeLieuLabel)
                    .addComponent(codeLieuField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(designationLabel)
                    .addComponent(designationField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(provinceLabel)
                    .addComponent(provinceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        operationPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Opérations", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Trebuchet MS", 1, 22), new java.awt.Color(236, 240, 241))); // NOI18N
        operationPanel.setOpaque(false);

        addButton.setBackground(new java.awt.Color(86, 101, 115));
        addButton.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        addButton.setForeground(new java.awt.Color(255, 250, 250));
        addButton.setText("Ajouter");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        editButton.setBackground(new java.awt.Color(86, 101, 115));
        editButton.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        editButton.setForeground(new java.awt.Color(255, 250, 250));
        editButton.setText("Modifier");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        deleteButton.setBackground(new java.awt.Color(86, 101, 115));
        deleteButton.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        deleteButton.setForeground(new java.awt.Color(255, 250, 250));
        deleteButton.setText("Supprimer");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        refreshButton.setBackground(new java.awt.Color(86, 101, 115));
        refreshButton.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        refreshButton.setForeground(new java.awt.Color(255, 250, 250));
        refreshButton.setText("Actualiser");
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout operationPanelLayout = new javax.swing.GroupLayout(operationPanel);
        operationPanel.setLayout(operationPanelLayout);
        operationPanelLayout.setHorizontalGroup(
            operationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(operationPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(operationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(operationPanelLayout.createSequentialGroup()
                        .addComponent(addButton, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(editButton, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE))
                    .addGroup(operationPanelLayout.createSequentialGroup()
                        .addComponent(deleteButton, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addComponent(refreshButton, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        operationPanelLayout.setVerticalGroup(
            operationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(operationPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(operationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(editButton, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(operationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteButton, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(refreshButton, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout bodyPanelLayout = new javax.swing.GroupLayout(bodyPanel);
        bodyPanel.setLayout(bodyPanelLayout);
        bodyPanelLayout.setHorizontalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(infoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(operationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(bodyPanelLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(searchPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(listPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE))
                .addContainerGap())
        );
        bodyPanelLayout.setVerticalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyPanelLayout.createSequentialGroup()
                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bodyPanelLayout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(infoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(operationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(bodyPanelLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(searchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(listPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 740, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(bodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(bodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
        if(!isEmpty(searchField)){
            String searchType=searchTypeComboBox.getSelectedItem().toString();
            List<Lieu> l=new ArrayList();

            if(searchType.equals("Code lieu")){
                if(estValide(searchField.getText())){
                    l.add(dao.obtenirLieu(searchField.getText()));
                    if(l.get(0)==null) JOptionPane.showMessageDialog(null, "Aucun lieu dont le "+searchType+"= '"+searchField.getText()+"' n'a été trouvé !", "Aucun résultat", JOptionPane.INFORMATION_MESSAGE);
                    else fillTableModel(l); //searchField.setText("");
                }else JOptionPane.showMessageDialog(null, "Le code lieu est invalide !", "Champs invalide", JOptionPane.WARNING_MESSAGE);
            }else{
                l=dao.listerLieuParMotCle(searchField.getText());
                if(l==null) JOptionPane.showMessageDialog(null, "Aucun lieu correspondant au "+searchType+"= '"+searchField.getText()+"' n'a été trouvé !", "Aucun résultat", JOptionPane.INFORMATION_MESSAGE);
                else fillTableModel(l); //searchField.setText("");
            }
        }else JOptionPane.showMessageDialog(null, "Le champs de recherche est vide !", "Champs vide", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_searchButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        if(isEmpty(designationField) || isEmpty(provinceField))
            JOptionPane.showMessageDialog(null, "Aucun des champs 'Designantion' ou 'Province' ne peut être laissé vide !", "Champs vide(s)", JOptionPane.WARNING_MESSAGE);
        else{
            if(dao.creerLieu(designationField.getText(), provinceField.getText())){
                String sms="Le lieu :\n"+
                                "\tDesignation = "+designationField.getText()+"\n"+
                                "\tProvince = "+provinceField.getText()+"\n"+
                            "a été ajouté avec succès !";
                JOptionPane.showMessageDialog(null, sms, "Succès de l'ajout", JOptionPane.INFORMATION_MESSAGE);
                addTableRow(dao.obtenirLieu(designationField.getText(), provinceField.getText()));
                eraseFields();
            }else JOptionPane.showMessageDialog(null, "Echec de l'ajout du nouveau lieu !", "Erreur d'ajout", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_addButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        // TODO add your handling code here:
        if(!isEmpty(codeLieuField)){
            if(isEmpty(designationField) || isEmpty(provinceField))
                JOptionPane.showMessageDialog(null, "Aucun des champs 'Designantion' ou 'Province' ne peut être laissé vide !", "Champs vide(s)", JOptionPane.WARNING_MESSAGE);
            else{
                if(JOptionPane.showConfirmDialog(null, "Voullez-vous enregistrer les modifications apportés au lieu dont le code est '"+codeLieuField.getText()+"' ?", "Confirmation de mise à jour",
                    JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE)== JOptionPane.YES_OPTION){
                    if(dao.mettreAjourLieu(codeLieuField.getText(), designationField.getText(), provinceField.getText())){
                        JOptionPane.showMessageDialog(null, "Les modifications ont été enregistrées avec succès !", "Succès de mise à jour", JOptionPane.INFORMATION_MESSAGE);
                        editTableRow(placeTable.getSelectedRow(), codeLieuField.getText(), designationField.getText(), provinceField.getText());
                        eraseFields();
                    }else JOptionPane.showMessageDialog(null, "Echec de l'enregistrement des modifications !", "Erreur de mise à jour", JOptionPane.ERROR_MESSAGE);
                }
            }
        }else JOptionPane.showMessageDialog(null, "Le champ 'Code' est vide !\nVeuillez selectionner un lieu dans le tableau", "Champs vide", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_editButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        if(!isEmpty(codeLieuField)){
            if(JOptionPane.showConfirmDialog(null, "Voullez-vous vraiment supprimer le lieu dont le code est = '"+codeLieuField.getText()+"' ?", "Confirmation de suppression",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE)== JOptionPane.YES_OPTION){
                if(dao.supprimerLieu(codeLieuField.getText())){
                    JOptionPane.showMessageDialog(null, "Le lieu a été supprimé avec succès !", "Succès de suppression", JOptionPane.INFORMATION_MESSAGE);
                    removeTableRow(placeTable.getSelectedRow());
                    eraseFields();
                }else JOptionPane.showMessageDialog(null, "Echec de la suppression du lieu !", "Erreur de suppression", JOptionPane.ERROR_MESSAGE);
            }
        }else JOptionPane.showMessageDialog(null, "Le champ 'Code' est vide !\nVeuillez selectionner un lieu dans le tableau", "Champs vide", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        // TODO add your handling code here:
        eraseFields();
        searchTypeComboBox.setSelectedIndex(0);
        fillTableModel(dao.listerLieu());
    }//GEN-LAST:event_refreshButtonActionPerformed

    private void placeTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_placeTableMouseClicked
        // TODO add your handling code here:
        try{
            move(placeTable.getSelectedRow());
        }catch(Exception ex){
            System.err.println("\nErreur causée par placeTableMouseClicked() de LieuPanel !\n"+ex);
        }
    }//GEN-LAST:event_placeTableMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JPanel bodyPanel;
    private javax.swing.JLabel byLabel;
    private javax.swing.JTextField codeLieuField;
    private javax.swing.JLabel codeLieuLabel;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTextField designationField;
    private javax.swing.JLabel designationLabel;
    private javax.swing.JButton editButton;
    private javax.swing.JPanel infoPanel;
    private javax.swing.JPanel listPanel;
    private javax.swing.JPanel operationPanel;
    private javax.swing.JTable placeTable;
    private javax.swing.JScrollPane placeTableScroll;
    private javax.swing.JTextField provinceField;
    private javax.swing.JLabel provinceLabel;
    private javax.swing.JButton refreshButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchField;
    private javax.swing.JPanel searchPanel;
    private javax.swing.JComboBox<String> searchTypeComboBox;
    // End of variables declaration//GEN-END:variables
}
